at its core pytorch is for processing of tensors


✨ A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions.
- Scalar → a single number (0D tensor)
- Vector → a list of numbers (1D tensor)
- Matrix → a grid of numbers (2D tensor)
- Tensor → an array of numbers that can extend to n dimensions


In [1]:
import torch

In [2]:
t1 = torch.tensor(1.)
t1
t1.dtype

torch.float32

In [3]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
t3 = torch.tensor([[5.,6],[4,7],[3,6]]) #matrix
t3

tensor([[5., 6.],
        [4., 7.],
        [3., 6.]])

In [ ]:
t4 = torch.tensor([[[1,2,3],[4,5,6]],[[4,5,3],[4,6,3]]])
t4

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 3],
         [4, 6, 3]]])

In [ ]:
#for 3 dimension we write one matrix below the other

In [ ]:
t1.shape


torch.Size([])

In [ ]:
t2.shape

torch.Size([4])

In [ ]:
t3.shape

torch.Size([3, 2])

In [ ]:
t4.shape
#for these kind of shapes go from outer brackets to inner brackets calculating element sizes

torch.Size([2, 2, 3])

In [ ]:
#backward() does the differentiation and forgrad = true should be set or else the varialbe wont be calculated

In [12]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad = True)
x, w, b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [13]:
y = w*x + b

### 🔹 requires_grad = True (PyTorch)

When we set `requires_grad=True` for a tensor, PyTorch starts tracking all the operations performed on it.  
So, if we perform a complex operation involving multiple tensors (each having `requires_grad=True`),  
PyTorch can automatically calculate the **partial derivatives** of the final output with respect to **each of those variables** during backpropagation.  
In short, it allows PyTorch to apply **automatic differentiation** and compute gradients for all variables involved.


In [ ]:
y.backward()

In [15]:
print(x.grad)#since we did not set requires grad = true it wont be keeping in the memory the values of x to calculate gradients
print(b.grad) #, now its only 3 variables but when they are millions this would be crazy optimization
print(w.grad)

None
tensor(1.)
tensor(3.)


In [16]:
#many tensor operations like sin , cat etc

In [17]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [18]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 4.,  7.],
        [ 3.,  6.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [19]:
t8 = torch.sin(t7)
t8


tensor([[-0.9589, -0.2794],
        [-0.7568,  0.6570],
        [ 0.1411, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

numpy interoperability , why do we need to use pytorch  ? pytorch provides autograd feature as mentioned above and gpu computation

In [20]:
import numpy as np

u = np.array(t1) #tensor to numpy
u
u.dtype

dtype('float32')

In [21]:
y = torch.from_numpy(u) #numpy to tensor
y
y.dtype

torch.float32