****Linear regression using PyTorch built in functions****

In [4]:
import torch.nn as nn
import numpy as np
import torch

In [5]:
input = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

target = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

In [6]:
input = torch.from_numpy(input)
target = torch.from_numpy(target)

In [7]:
from torch.utils.data import TensorDataset

In [11]:
train_ds = TensorDataset(input,target)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

# 🧠 Understanding TensorDataset and DataLoader in PyTorch

In PyTorch, **`TensorDataset`** and **`DataLoader`** are used together to efficiently manage and feed data into models during training.

---

## 🔹 1. TensorDataset

`TensorDataset` combines multiple tensors (like inputs and labels) into a single dataset object.  
Each sample returned by indexing (`dataset[i]`) is a tuple containing corresponding elements from each tensor.

### ✨ Example

```python
import torch
from torch.utils.data import TensorDataset

# Sample input and output tensors
X = torch.tensor([[1,2], [3,4], [5,6], [7,8]])
y = torch.tensor([0, 1, 0, 1])

# Combine into a dataset
dataset = TensorDataset(X, y)

# Accessing individual samples
print(dataset[0])  # (tensor([1, 2]), tensor(0))
print(dataset[1])  # (tensor([3, 4]), tensor(1))


# ⚙️ Understanding DataLoader in PyTorch

The **`DataLoader`** in PyTorch is used to load data efficiently during model training.  
It wraps around a dataset (like a `TensorDataset` or a custom one) and provides features like **batching**, **shuffling**, and **parallel loading**.

---

## 🔹 1. Why Use DataLoader?

When training deep learning models, we usually:
- Don’t feed all data at once (memory-heavy),
- Instead, use **mini-batches** of data.

`DataLoader` automates this process by:
✅ Splitting data into batches  
✅ Optionally shuffling each epoch  
✅ Feeding batches one by one to the model

---

## 🔹 2. Basic Example

```python
import torch
from torch.utils.data import TensorDataset, DataLoader

# Create some sample data
X = torch.tensor([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
y = torch.tensor([0, 1, 0, 1, 0, 1])

# Create a TensorDataset
dataset = TensorDataset(X, y)

# Wrap it in a DataLoader
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)


In [13]:
from torch.utils.data import DataLoader

In [14]:
batch_size = 5
train_d1 = DataLoader(train_ds,batch_size,shuffle = True)

In [17]:
for xb,yb in train_d1:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.]])
tensor([[ 22.,  37.],
        [ 56.,  70.],
        [119., 133.],
        [119., 133.],
        [103., 119.]])


it has randomly used 5 values because 5 is the batch size and we have set shuffle = true

         ┌──────────────────────────────┐
         │        Raw Tensors           │
         │   X → Inputs,  y → Labels    │
         └──────────────┬───────────────┘
                        │
                        ▼
         ┌──────────────────────────────┐
         │       TensorDataset          │
         │ Pairs each (X[i], y[i])      │
         │ → [(x₁,y₁), (x₂,y₂), ...]    │
         └──────────────┬───────────────┘
                        │
                        ▼
         ┌──────────────────────────────┐
         │          DataLoader          │
         │ - Shuffles data (if True)    │
         │ - Splits into batches        │
         │ - Prepares for iteration     │
         └──────────────┬───────────────┘
                        │
                        ▼
      ┌────────────────────────────────────────┐
      │        During Training Loop            │
      │ for X_batch, y_batch in dataloader:    │
      │     → Model receives mini-batch        │
      │     → Forward pass                     │
      │     → Loss calculation                 │
      │     → Backward pass                    │
      └────────────────────────────────────────┘


**LINEAR MODULE** instead of initializing weights and biases manually we can define the model using the nn.Linear class which does it automatically

linear is one of the model in pytorch for linear regression moving on we have many like nn.convolution and all 

In [24]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1108,  0.1982, -0.2847],
        [-0.3553,  0.2865,  0.4303]], requires_grad=True)
Parameter containing:
tensor([-0.0232,  0.0763], requires_grad=True)


pytoch models also have a helpful **.parameters** method which returns a list containing all the weights and bias matrices present in the model. for out linear regression model we have one wiehgt matrix and one bias 

In [25]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1108,  0.1982, -0.2847],
         [-0.3553,  0.2865,  0.4303]], requires_grad=True),
 Parameter containing:
 tensor([-0.0232,  0.0763], requires_grad=True)]

In [26]:
#generating predections
preds = model(input)
preds

tensor([[ 9.1032, 11.8373],
        [ 9.2809, 20.4943],
        [19.6628, 32.5128],
        [ 9.2690, -7.9239],
        [ 6.7198, 33.1843],
        [ 9.1032, 11.8373],
        [ 9.2809, 20.4943],
        [19.6628, 32.5128],
        [ 9.2690, -7.9239],
        [ 6.7198, 33.1843],
        [ 9.1032, 11.8373],
        [ 9.2809, 20.4943],
        [19.6628, 32.5128],
        [ 9.2690, -7.9239],
        [ 6.7198, 33.1843]], grad_fn=<AddmmBackward0>)

loss function with built function mse_loss

the nn.functional package contains many usefull loss functoins and several other utilities

In [28]:
import torch.nn.functional as F

In [29]:
loss_fn = F.mse_loss

In [30]:
loss = loss_fn(model(input),target)
print(loss)

tensor(5598.7017, grad_fn=<MseLossBackward0>)


****OPTIMIZERS**** instead of manually doing the gradient descent we use optim.SGD sgd is stochastic gradient descent 

In [33]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)
#defining optimizer

## Train the model

We are now ready to train the model. We'll follow the exact same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data, instead of processing the entire training data in every iteration. Let's define a utility function `fit` which trains the model for a given number of epochs.

In [34]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_d1:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

# ⚙️ Does the Optimizer Run Epochs Automatically in PyTorch?

A common doubt when learning PyTorch is:

> ❓ *“Does the optimizer (like `optim.SGD`) automatically run all the epochs and give optimized weights?”*

---

## ❌ No — The Optimizer Doesn’t Run Epochs by Itself

The **optimizer** (e.g. `torch.optim.SGD`, `Adam`, etc.)  
does **not** control training epochs or loops.

It only performs **one single update step** each time you call:

```python
optimizer.step()


Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update, and opt.zero_grad to reset the gradients to zero.

In [35]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 220.6802
Epoch [20/100], Loss: 163.3108
Epoch [30/100], Loss: 154.2873
Epoch [40/100], Loss: 38.2649
Epoch [50/100], Loss: 4.8886
Epoch [60/100], Loss: 57.2609
Epoch [70/100], Loss: 60.3672
Epoch [80/100], Loss: 15.8552
Epoch [90/100], Loss: 26.3844
Epoch [100/100], Loss: 18.5895


In [36]:
# Generate predictions
preds = model(input)
preds

tensor([[ 58.6152,  70.8488],
        [ 79.0505,  99.7146],
        [123.4146, 134.3021],
        [ 29.2151,  39.9129],
        [ 91.6874, 115.7973],
        [ 58.6152,  70.8488],
        [ 79.0505,  99.7146],
        [123.4146, 134.3021],
        [ 29.2151,  39.9129],
        [ 91.6874, 115.7973],
        [ 58.6152,  70.8488],
        [ 79.0505,  99.7146],
        [123.4146, 134.3021],
        [ 29.2151,  39.9129],
        [ 91.6874, 115.7973]], grad_fn=<AddmmBackward0>)

In [38]:
# Compare with targets
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])